### ISSUE TITLE
Using with RTL-SDR on GNU/Linux

### ISSUE THREAD

**Issue by aocard** [martinmarinov/TempestSDR#49] opened 2021-12-03 22:10 UTC
To follow up on issue #7,
would it be possible to use this with RTL-SDR on Linux?

**Comment by mgkuhn** [comment] 2021-12-06 13:54
Duplicate of #7: yes, people have used that receiver, but its (in comparison with the targeted pixel clock rate) tiny maximum bandwidth and sampling rate will only give you very blurry images at best. So essentially only suited for demos with very large fonts and carefully chosen foreground/background RGB combinations.

**Closed by mgkuhn** 2021-12-06 13:54 UTC
